# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3

matrix:
  include:
    - os: linux
      julia: nightly

  exclude:
    - os: windows
      julia: 1.2

    - os: windows
      julia: 1.0
